### ISSUE TITLE
How to use different versions for different recipes?

### ISSUE THREAD

**Issue by sprhawk** [rust-embedded/meta-rust-bin#118]
Some recipes requires some more recent stable rust version, but other preferred some older ones or nightly.
Can I use some way like `PREFERRED_VERSION` to choose different rust versions for different recipes?

**Comment by nastevens** [comment]
Take a look at [bitbake multiconfig](https://www.yoctoproject.org/docs/latest/bitbake-user-manual/bitbake-user-manual.html#executing-a-multiple-configuration-build). This lets you specify multiple sets of "global" options and you can use this to set different `PREFERRED_VERSION`s for different targets.

In general you can create a multiconfig in your `conf` directory like `multiconfig/rust150.conf`. Then in that file:
```
PREFERRED_VERSION_rust-bin-cross-arm = "1.50.0"
PREFERRED_VERSION_cargo-bin-cross-arm = "1.50.0"
```

Then when you build you can specify the multiconfig target to use. So if you want to build `foo` with the Rust 1.50 multiconfig, you can do:
```
bitbake multiconfig:rust150:foo
```

There's more to it obviously so do check the docs linked above!

**Comment by sprhawk** [comment]
> Take a look at [bitbake multiconfig](https://www.yoctoproject.org/docs/latest/bitbake-user-manual/bitbake-user-manual.html#executing-a-multiple-configuration-build). This lets you specify multiple sets of "global" options and you can use this to set different `PREFERRED_VERSION`s for different targets.
> 
> In general you can create a multiconfig in your `conf` directory like `multiconfig/rust150.conf`. Then in that file:
> 
> ```
> PREFERRED_VERSION_rust-bin-cross-arm = "1.50.0"
> PREFERRED_VERSION_cargo-bin-cross-arm = "1.50.0"
> ```
> 
> Then when you build you can specify the multiconfig target to use. So if you want to build `foo` with the Rust 1.50 multiconfig, you can do:
> 
> ```
> bitbake multiconfig:rust150:foo
> ```
> 
> There's more to it obviously so do check the docs linked above!

I saw it. but I think that is used to build multiple variant targets with a same base config. If it is what I thought, this is not precisely what I mean.

I got `foo_git.bb` and `bar_git.bb`, and `foo` requires `rust 1.50`, and `bar` requires `nightly`, I want the `bitbake` system can choose `rust 1.50` to build `foo`, and use `nightly` to build `bar`

**Comment by nastevens** [comment]
Unfortunately as far as I know there's not a way to have multiple versions of a package installed at the same time. In this case the package in question would be `rust-bin-cross-arm` and `cargo-bin-cross-arm`. Gentoo (where Bitbake originated from many years ago) has the idea of "slots" that allow you have parallel versions of packages installed, but I couldn't find anything similar for Bitbake.

I agree that the docs refer to the multiconfig for multiple targets, but I've actually used multiconfig on a project to good effect for building some packages fully statically linked with musl and everything else with glibc and dynamic linking.
