### ISSUE TITLE
release branches and compatibility

### ISSUE THREAD

**Issue by bernardoaraujor** [rust-embedded/meta-rust-bin#53]
I see the repository currently contains only two branches: `master` and `dizzy`.
Meanwhile `conf/layer.conf` lists `LAYERSERIES_COMPAT_rust-bin-layer = "sumo rocko"`.

Perhaps that could be improved, as it is can be a bit confusing the way it is now.

Also, is there planned support for thud and warrior?

**Comment by posborne** [comment]
@bernardoaraujor We suspect things may work with those version already but we haven't tested as of yet based on the projects that @nastevens and I are working on presently.  If you are able to add those and test then we would gladly support either the compat adjustment and/or additional patches to support these versions.
