### ISSUE TITLE
rustc is stuck inside devshell, but work when execute build task

### ISSUE THREAD

**Issue by sprhawk** [rust-embedded/meta-rust-bin#73]
I'm using poky dunfell branch, use HEAD revision of meta-rust-bin.
I can do `bitbake my-rust-project-recipe`,  
but when `bitbake -c devshell my-rust-projet-recipe`, inside devshell, execute `rustc` with any parameters even `--version`, it will stuck, no any output. 

`cargo --version` can work, but `cargo build` still stuck.

my target is aarch64 (Raspberry Pi 4) host is Debian Buster x86_64.

**Comment by posborne** [comment]
Closing as stale, please reopen if this is still an issue you are seeing @sprhawk
