### ISSUE TITLE
How to specify a certain version of rustc

### ISSUE THREAD

**Issue by hellow554** [rust-embedded/meta-rust-bin#89]
What information should I include in my recipe, do tell yocto which version of rust it should use? E.g. I want my code to compile with Rust 1.43.0, (e.g. because of a regression).

**Comment by nastevens** [comment]
@hellow554 You can use `PREFERRED_VERSION` for the `rust-bin-cross-*` and `cargo-bin-cross-*` recipes. For example, for if my target is ARM:

```
PREFERRED_VERSION_rust-bin-cross-arm ?= "1.43.0"
PREFERRED_VERSION_cargo-bin-cross-arm ?= "${PREFERRED_VERSION_rust-bin-cross-arm}"
```

**Comment by hellow554** [comment]
Thanks! Would this something for the readme?

**Comment by sprhawk** [comment]
Please try this PR: https://github.com/rust-embedded/meta-rust-bin/pull/109
